"""Render the Wave-2 research reports (Markdown) from their JSON. RESEARCH_ONLY.

Every number in a generated report comes from its JSON; `scripts/sim/wave2_render.py --check` fails when a committed
Markdown file differs from what its JSON renders to, so a report can never drift from its data.
"""
from __future__ import annotations

import json
import os

HEADER = ("<!-- GENERATED by scripts/sim/wave2_render.py from {src}; do not edit by hand -->\n\n"
          "**RESEARCH_ONLY.** Nothing here controls BET/PASS, a probability, a price limit, a stake, a unit size or a "
          "reconciliation weight.\n\n")
STATUS_HELP = {
    "PROSPECTIVE_CHALLENGER": "passed its development selection and mechanism check; its contaminated diagnostic did not show the primary metric worse; it now accumulates frozen prospective records. It is NOT validated.",
    "REJECTED_AT_DEVELOPMENT": "failed a preregistered development criterion; prospective records, if captured, are descriptive only and cannot promote it under this preregistration.",
    "DIAGNOSTIC_FAIL": "passed development but the contaminated 2021-2025 diagnostic showed the primary metric worse.",
    "COLLECTING": "design frozen; prospective observations are accumulating; no result is read before the minimum sample.",
}


def f(x, nd=3):
    if x is None:
        return "n/a"
    if isinstance(x, bool):
        return "yes" if x else "no"
    if isinstance(x, int):
        return str(x)
    return f"{x:.{nd}f}"


def pct(x, nd=2):
    return "n/a" if x is None else f"{100 * x:+.{nd}f}%"


def ci(d, nd=4, scale=1.0, unit=""):
    return f"{d['mean'] * scale:+.{nd}f}{unit} [{d['lo'] * scale:+.{nd}f}, {d['hi'] * scale:+.{nd}f}]"


def table(head, rows):
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out) + "\n"


def findings(d):
    return ("## Findings\n\n" + "".join(f"* {x}\n" for x in d["findings"]) + "\n") if d.get("findings") else ""


def status_block(st, criteria=None):
    out = f"**Status: {st}** — {STATUS_HELP.get(st, '')}\n\n"
    failed = [k for k, v in (criteria or {}).items() if v is False]
    if failed:
        out += "Failed development criteria: " + ", ".join(f"`{k}`" for k in failed) + ".\n\n"
    return out


def stat_rows(stats: dict, keys=None):
    rows = []
    for s in keys or sorted(stats):
        if s not in stats:
            continue
        r = stats[s]
        rows.append([s, r["n"], f(r["crps_a0"]), f(r["crps_arm"]), pct(r["rel_crps"]), pct(r["mae_arm"] / r["mae_a0"] - 1),
                     f(r["bias_a0"]), f(r["bias_arm"]), f(r["chi2_a0"], 1), f(r["chi2_arm"], 1),
                     f(r["low_decile_a0"]), f(r["low_decile_arm"]), f(r["high_decile_a0"]), f(r["high_decile_arm"]),
                     f(r["cover90_a0"]), f(r["cover90_arm"])])
    return table(["stat", "n", "CRPS A0", "CRPS arm", "rel CRPS", "rel MAE", "bias A0", "bias arm", "chi2 A0", "chi2 arm",
                  "P(rPIT<.1) A0", "arm", "P(rPIT>.9) A0", "arm", "cover90 A0", "arm"], rows)


def min_sample_line(ms, status=None):
    if status in ("REJECTED_AT_DEVELOPMENT", "DIAGNOSTIC_FAIL"):
        n = (ms or {}).get("n_games")
        return (f"Minimum prospective sample: **not applicable** — the arm is {status}; the section-8 formula would give "
                f"{n} games, recorded for completeness only.\n\n")
    if not ms or ms.get("n_games") is None:
        return f"Minimum prospective sample: **not defined** ({(ms or {}).get('reason', 'no development effect')}).\n\n"
    extra = f" ({ms['n_weeks']} weeks of 16, ~{ms['n_seasons_at_285']} seasons)" if "n_weeks" in ms else ""
    return (f"Minimum prospective sample (PREREGISTRATION section 8, from the 2020 development effect {f(ms['effect'], 4)} "
            f"and between-game sd {f(ms['sd'], 4)}): **{ms['n_games']} games**{extra}.\n\n")


# ------------------------------------------------------------------------------------------------------- S1
def render_s1(d, src="S1_SHARE_DISPERSION.json"):
    crit = {k: v for k, v in d["development_mechanism_check"]["criteria"].items() if isinstance(v, bool)}
    o = [f"# S1 — concentration-conditioned opportunity dispersion\n\n", HEADER.format(src=src), status_block(d["status"], crit)]
    o.append("Evidence: DEVELOPMENT = 2020 (bundle trained 2018-2019, selection on 2020 likelihood); CONTAMINATED_DIAGNOSTIC = "
             "2021-2025 (description only, never validation). Comparison: S1 vs the incumbent on IDENTICAL rows "
             "(the incumbent's scored population), game-clustered intervals.\n\n")
    o.append("## Development selection (Dirichlet-multinomial likelihood, 2020 per team-game)\n\n")
    rows = []
    for fam, v in d["selection"].items():
        rows.append([fam, f(v["incumbent_alpha_moment"], 2), f(v["S1_0_alpha_ml"], 2), ci(v["S1_0_minus_incumbent"]), ci(v["S1_1_minus_S1_0"]),
                     v["selected"], v["status"]])
    o.append(table(["family", "incumbent alpha (moments)", "S1-0 alpha (likelihood)", "S1-0 − incumbent", "S1-1 − S1-0", "selected", "status"], rows))
    o.append("\nThe incumbent's moment estimate on realised shares counts the multinomial noise twice, so its concentration is "
             "too LOW (too much dispersion); maximum likelihood on counts raises it markedly, and conditioning on concentration "
             "features adds a further gain (larger for carries than for targets). Log-likelihood differences are per team-game.\n\n")
    m = d["development_mechanism_check"]
    o.append("## Development mechanism check (full simulation of 2020)\n\n")
    o.append(f"Primary (mean relative CRPS of the five opportunity statistics): **{ci(m['primary'], 3, 100, '%')}** "
             f"over {m['primary']['n_games']} games.\n\n")
    o.append(table(["criterion", "value"], [[k, f(v) if not isinstance(v, int) or isinstance(v, bool) else v] for k, v in m["criteria"].items()]))
    o.append("\n" + stat_rows(m["by_stat"]))
    c = d["contaminated_diagnostic"]
    o.append("\n## Contaminated diagnostic 2021-2025 (descriptive)\n\n")
    o.append(f"Pooled primary: {ci(c['pooled']['primary'], 3, 100, '%')} over {c['pooled']['primary']['n_games']} games.\n\n")
    o.append(table(["season", "primary (rel CRPS of the five)", "games"],
                   [[y, ci(v["primary"], 3, 100, "%"), v["primary"]["n_games"]] for y, v in c["by_season"].items()]))
    o.append("\n" + stat_rows(c["pooled"]["stats"]))
    o.append("\n### Subgroups (descriptive; definitions fixed in PREREGISTRATION section 2)\n\n")
    rows = []
    for g, st in c["subgroups"].items():
        n = sum(r["n"] for r in st.values())
        mean_rel = sum(r["rel_crps"] for r in st.values()) / max(1, len(st))
        chi = "; ".join(f"{s} {f(r['chi2_a0'], 0)}→{f(r['chi2_arm'], 0)}" for s, r in st.items())
        rows.append([g, n, pct(mean_rel), chi])
    o.append(table(["subgroup", "rows", "mean rel CRPS of the five", "chi2 A0→S1"], rows))
    worse = [r for r in rows if r[2].startswith("+")]
    o.append("\n**Where S1 is worse:** " + ("; ".join(f"{r[0]} ({r[1]} rows, {r[2]})" for r in worse) if worse else "no subgroup") +
             ". Descriptive (contaminated seasons); S1 is not claimed to help there.\n" if worse else "\nNo preregistered subgroup is worse under S1.\n")
    o.append("\n" + min_sample_line(d["minimum_prospective_sample"], d["status"]))
    o.append("## Frozen 2026 components\n\n")
    o.append(table(["family", "form", "base alpha", "trained on"],
                   [[k, v["form"], f(v["base_alpha"], 2), f"{v['train_seasons'][0]}-{v['train_seasons'][-1]}"]
                    for k, v in d["frozen_2026_components"].items()]))
    o.append("\nExpected shares, team volume, OTHER and availability are untouched; only the concentration changes.\n")
    return "".join(o)


# ------------------------------------------------------------------------------------------------------- Q1
def render_q1(d, src="Q1_QB_EXIT_TAIL.json"):
    crit = {k: v for k, v in d["development_mechanism_check"]["criteria"].items() if isinstance(v, bool)}
    o = [f"# Q1 — quarterback starter-share regimes (exit tail)\n\n", HEADER.format(src=src), status_block(d["status"], crit)]
    o.append(findings(d))
    s = d["selection"]
    o.append("## Development selection (fit 2018-2019, score 2020)\n\n")
    o.append(table(["quantity", "value"], [
        ["conditional − unconditional log loss", ci(s["conditional_minus_unconditional"])],
        ["unconditional − incumbent-implied log loss", ci(s["unconditional_minus_incumbent_implied"])],
        ["selected form", s["selected"]],
        ["regime counts train (FULL, PARTIAL, LOW)", s["regime_frequency"]["train"]],
        ["regime counts 2020", s["regime_frequency"]["2020"]],
        ["incumbent-implied regime frequency", [round(x, 4) for x in s["incumbent_implied_regime_frequency"]]],
        ["IDENTIFICATION ERROR rate (train / 2020)", f"{f(s['identification_error_rate']['train'])} / {f(s['identification_error_rate']['2020'])}"],
        ["EXIT / PARTIAL rate (train / 2020)", f"{f(s['exit_partial_rate']['train'])} / {f(s['exit_partial_rate']['2020'])}"],
    ]))
    m = d["development_mechanism_check"]
    o.append("\n## Development mechanism checks (2020)\n\n")
    o.append(f"Primary (change in lower-decile calibration error, negative = closer to 0.10): **{ci(m['primary_delta_lower_decile_error'])}**.\n\n")
    crit = [[k, f(v)] for k, v in m["criteria"].items() if k != "regime_bands_2020"]
    o.append(table(["criterion", "value"], crit))
    o.append("\n" + table(["regime", "observed 2020", "90% predictive band", "binomial band", "inside"],
                          [[k, v["observed_2020"], v["band90"], v["binomial_band90"], f(v["inside"])] for k, v in m["criteria"]["regime_bands_2020"].items()]))
    o.append("\n" + stat_rows(m["by_stat"]))
    o.append("\nReceivers downstream (expected unchanged in distribution): " +
             "; ".join(f"{k} rel CRPS {pct(v['rel_crps'], 3)}" for k, v in m["receivers_downstream"].items()) + ".\n\n")
    c = d["contaminated_diagnostic"]
    o.append("## Contaminated diagnostic 2021-2025 (descriptive)\n\n")
    o.append(table(["season", "primary Δ lower-decile error", "games"],
                   [[y, ci(v["primary"]), v["primary"]["n_games"]] for y, v in c["by_season"].items()] +
                   [["pooled", ci(c["pooled"]["primary"]), c["pooled"]["primary"]["n_games"]]]))
    o.append("\n" + stat_rows(c["pooled"]["stats"]))
    o.append("\n" + min_sample_line(d["minimum_prospective_sample"], d["status"]))
    o.append(f"Note: {d['note']}.\n")
    return "".join(o)


# ------------------------------------------------------------------------------------------------------- A1
def render_a1(d, src="A1_AVAILABILITY_HORIZONS.json"):
    o = [f"# A1 — information-horizon-correct availability\n\n", HEADER.format(src=src), status_block(d["status"], d["development_mechanism_check"])]
    o.append(findings(d))
    o.append("Horizons: " + "; ".join(d["horizons"]) + ".\n\nEvery comparison is against the incumbent historical "
             "backtest (T0_GAMEDAY_INACTIVES_WITH_Q_DISCOUNT) on identical rows.\n\n")
    for ph in ("development", "contaminated_diagnostic"):
        o.append(f"## {ph.replace('_', ' ').capitalize()}\n\n")
        for hz in ("T0_INACTIVES", "T24"):
            b = d[ph][hz]
            o.append(f"### {hz}\n\nPrimary (change in |bias| of questionable players' carries + targets; negative = less biased): "
                     f"**{ci(b['primary_delta_abs_bias'])}**.\n\n")
            if len(b["by_season_primary"]) > 1:
                o.append(table(["season", "change in abs bias"], [[y, ci(v)] for y, v in b["by_season_primary"].items()]) + "\n")
            for grp in ("questionable_players", "teammates_of_questionable"):
                o.append(f"*{grp.replace('_', ' ')}*\n\n" + stat_rows(b[grp]) + "\n")
    o.append("## Development criteria\n\n" + table(["criterion", "value"], [[k, f(v)] for k, v in d["development_mechanism_check"].items()]))
    o.append("\n" + min_sample_line(d.get("minimum_prospective_sample"), d["status"]))
    o.append(f"Note: {d['note']}.\n")
    return "".join(o)


# ------------------------------------------------------------------------------------------------------- M1
def render_m1(d, src="M1_KEY_NUMBERS.json"):
    o = [f"# M1 — key-number-aware margin distribution\n\n", HEADER.format(src=src), status_block(d["status"])]
    p = d["parameters"]
    o.append(f"Version {d['m1_version']}. History {d['fit_window']}. M1-K: kernel h_spread {p['h_spread']}, h_total {p['h_total']}, "
             f"season half-life {p['halflife']}, effective n >= {p['min_eff_n']}, exponential tilt to the centre. "
             f"M1-S: ±{p['strat_half_width']} points, n >= {p['strat_min_n']}.\n\n")
    o.append("## Key numbers that emerge from <= 2020 (reported, never imposed)\n\n")
    o.append(table(["abs margin", "frequency", "smoothed", "z"],
                   [[k["abs_margin"], f(k["freq"], 4), f(k["smoothed"], 4), f(k["z"], 1)] for k in d["emergent_key_numbers_le_2020"]]))
    for ph, lab in (("development", "Development (rolling origin 2018-2020)"), ("contaminated_diagnostic", "Contaminated diagnostic 2021-2025 (descriptive)")):
        b = d[ph]
        o.append(f"\n## {lab}\n\n")
        rows = [[m, f(v["log_score"], 4), f(v["ladder_brier"], 5), f(v["total_ladder_brier"], 5), f(v["v2_multiclass_brier"], 4),
                 f(v["mean_abs_centre_error"], 3), f(v["p_exact_abs3"], 4), f(v["coherent_all_games"])] for m, v in b["pooled"]["models"].items()]
        o.append(f"Pooled over {b['pooled']['n_games']} games; realised share of abs margin = 3: {f(b['pooled']['realized_abs3_share'], 4)}.\n\n")
        o.append(table(["model", "log score", "spread-ladder Brier", "total-ladder Brier", "V2 Brier", "mean abs centre error", "P(abs m = 3)", "coherent"], rows))
        o.append("\n" + table(["candidate − M0", "log score", "spread ladder", "total ladder", "V2 Brier"],
                              [[m, ci(v["log_score"]), ci(v["ladder_brier"], 5), ci(v["total_ladder_brier"], 5), ci(v["v2_multiclass_brier"])]
                               for m, v in b["pooled"]["vs_M0"].items()]))
        o.append("\n" + table(["season", "M1-K − M0 log score", "games"],
                              [[y, ci(v["vs_M0"]["M1-K"]["log_score"]), v["n_games"]] for y, v in b["by_season"].items()]))
    s = d["selection"]
    o.append(f"\nSelection: {s['rule']}; selected **{s['selected']}**.\n\n")
    a = d["incumbent_audit_2020"]
    o.append("## Incumbent residual-bank audit (2020)\n\n")
    o.append(table(["model", "games with any negative team score row", "mean share of rows", "max share"],
                   [[m, v["games_with_any"], f(v["mean_share_rows"], 4), f(v["max_share_rows"], 4)] for m, v in a["negative_team_score_rows"].items()]))
    o.append(f"\nIncumbent mean abs(simulated mean margin − centre): {f(a['mean_abs_centre_error_points'], 3)} points.\n\n")
    o.append(min_sample_line(d["minimum_prospective_sample"], d["status"]))
    return "".join(o)


# ------------------------------------------------------------------------------------------------------- RISK1
def render_risk1(d, src="RISK1_SCRIPT_ROBUSTNESS.json"):
    o = [f"# RISK1 — script robustness and thesis concentration\n\n", HEADER.format(src=src), status_block(d["status"])]
    o.append(f"Authority: {d['authority']}. Version {d['version']}. Prospective cutoff {d['prospective_cutoff']}.\n\n")
    o.append("## Design (frozen in PREREGISTRATION section 6)\n\n")
    o.append(f"* Primary test: {d['primary_test']}.\n* Measures: {', '.join(d['measures'])}.\n"
             f"* Thesis grouping: fingerprint Jaccard of winning rows >= {d['thesis_jaccard_threshold']}; effective_theses = 1 / sum(w^2).\n\n")
    c = d["capture"]
    o.append("## Collection status\n\n")
    o.append(table(["item", "value"], [["source", c["source"]], ["GAME SCRIPT V2 captures listed at build", c["captures_seen_at_build"]],
                                       ["captures generated after the cutoff", c["captures_after_cutoff_at_build"]],
                                       ["fingerprints", c["fingerprints"]], ["listing ref", c["listing_ref"]]]))
    ms = d["minimum_prospective_sample"]
    o.append("\n## Minimum prospective sample\n\n")
    o.append(f"From {ms['source']}: {ms['n_contracts_in_study']} contracts; per-game contrast sd {f(ms['per_game_contrast_sd'], 4)}; "
             f"minimal effect {ms['minimal_effect']} → **{ms['n_games']} games ({ms['n_weeks_at_16']} weeks of 16)**. "
             f"That is ~{ms['n_games'] / 285:.1f} seasons: the preregistered UNDERPOWERED label (more than two seasons) "
             f"{'applies' if ms['underpowered_at_one_season'] else 'does not apply'}, but the test cannot complete within the "
             f"2026 season alone. The primary test is not run before "
             f"this many prospective games carry a frozen capture.\n\n")
    o.append(f"Development contrast (NOT evidence): {f(d['development_contrast_2020']['per_game_contrast_mean'], 4)} — "
             f"{d['development_contrast_2020']['note']}.\n\n")
    o.append(f"Results: {'none yet' if d['results'] is None else d['results']}.\n")
    return "".join(o)


RENDERERS = {"S1_SHARE_DISPERSION": render_s1, "Q1_QB_EXIT_TAIL": render_q1, "A1_AVAILABILITY_HORIZONS": render_a1,
             "M1_KEY_NUMBERS": render_m1, "RISK1_SCRIPT_ROBUSTNESS": render_risk1}


def render_file(json_path: str) -> str:
    name = os.path.splitext(os.path.basename(json_path))[0]
    return RENDERERS[name](json.load(open(json_path)), src=os.path.basename(json_path))
