#!/usr/bin/env python3
"""research/pure_gap/decomposition.json -> research/pure_gap/DECOMPOSITION_TABLES.md (every number in the doc)."""
from __future__ import annotations

import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
STATS = ["snap_share", "targets", "receptions", "receiving_yards", "carries", "rushing_yards", "passing_attempts", "completions",
         "passing_yards"]
LADDER = [("PURE_minus_V4_MEF_NO_AVAIL", "(1) model structure, sports-only: PURE − V4 without availability / market"),
          ("availability_features__V4_NO_AVAIL_minus_V4_MEF", "(2) availability features: V4_NO_AVAIL − V4_MEF"),
          ("market_environment__V4_MEF_minus_V4_MKT", "(3) market environment: V4_MEF − V4_MKT")]


def f(s, d=4):
    if not s or s.get("mean") is None:
        return "—"
    ci = s.get("ci95")
    sig = "" if not ci else ("**" if ci[0] > 0 or ci[1] < 0 else "")
    return f"{sig}{s['mean']:+.{d}f}{sig} [{ci[0]:+.{d}f}, {ci[1]:+.{d}f}]" if ci else f"{s['mean']:+.{d}f}"


def dp(stat):
    return 2 if "yards" in stat else 4


def main(path, out):
    r = json.load(open(path))
    L = ["# PURE gap decomposition — full tables", "",
         "Generated by `scripts/research/pure_gap_render.py` from `decomposition.json`. Δ = first arm − second arm in MAE of "
         "the forecast mean (positive = first arm worse); 95% paired, game-clustered bootstrap CI (B = 1000); **bold** = CI "
         "excludes 0. 2024 + 2025 regular season, matched rows only.", ""]
    L += ["## Arm MAE and the additive ladder (PURE − V4_MARKET_CLOSE = (1) + (2) + (3), exactly)", "",
          "| statistic | n | games | MAE PURE | MAE V4_NO_AVAIL | MAE V4_MEF | MAE V4_MKT | PURE − V4_MKT | (1) structure | (2) availability | (3) market env |",
          "|---|---|---|---|---|---|---|---|---|---|---|"]
    for st in STATS:
        x = r["player"][st]; m = x["mae"]; s = x["shapley"]; d = dp(st)
        L.append(f"| {st} | {x['n']:,} | {x['n_games']} | {m['PURE_PLAYER_V1']:.{d}f} | {m['V4_MEF_NO_AVAIL']:.{d}f} | {m['V4_MEF_AS_IS']:.{d}f} | "
                 f"{m['V4_MARKET_CLOSE']:.{d}f} | {f(s['PURE_minus_V4_MARKET_CLOSE']['gap'], d)} | " + " | ".join(f(s[p]['gap'], d) for p, _ in LADDER) + " |")
    L += ["", "## Component split of each paired gap (Shapley over volume / snap / usage / efficiency hybrids)", ""]
    for p, lab in [("PURE_minus_V4_MARKET_CLOSE", "PURE − V4_MARKET_CLOSE"), ("PURE_minus_V4_MEF_AS_IS", "PURE − V4_MEF_AS_IS")] + LADDER:
        L += [f"### {lab}", "", "| statistic | gap | volume | snap | usage | efficiency |", "|---|---|---|---|---|---|"]
        for st in STATS:
            s = r["player"][st]["shapley"][p]; c = s["components"]; d = dp(st)
            L.append(f"| {st} | {f(s['gap'], d)} | " + " | ".join(f(c.get(k), d) for k in ("volume", "snap", "usage", "efficiency")) + " |")
        L.append("")
    L += ["## By season (gap only)", "", "| statistic | season | PURE − V4_MKT | (1) structure | (2) availability | (3) market env |", "|---|---|---|---|---|---|"]
    for st in STATS:
        for se, v in r["player"][st]["shapley_by_season"].items():
            d = dp(st)
            L.append(f"| {st} | {se} | {f(v['PURE_minus_V4_MARKET_CLOSE'], d)} | " + " | ".join(f(v[p], d) for p, _ in LADDER) + " |")
    L += ["", "## By position group (PURE − V4_MEF_AS_IS)", "", "| statistic | group | n | gap | volume | snap | usage | efficiency |", "|---|---|---|---|---|---|---|---|"]
    for st in STATS:
        for grp, v in r["player"][st]["shapley_by_group"].items():
            s = v["PURE_minus_V4_MEF_AS_IS"]; c = s["components"]; d = dp(st)
            L.append(f"| {st} | {grp} | {s['n']:,} | {f(s['gap'], d)} | " + " | ".join(f(c.get(k), d) for k in ("volume", "snap", "usage", "efficiency")) + " |")
    L += ["", "## Each arm's own error, split by component (oracle Shapley: share of MAE removed by the realised component)", "",
          "| statistic | arm | MAE | volume | snap | usage | efficiency |", "|---|---|---|---|---|---|---|"]
    for st in STATS:
        for a, o in r["player"][st]["oracle"].items():
            sh = o["share_of_mae"]
            L.append(f"| {st} | {a} | {o['mae']:.{dp(st)}f} | " + " | ".join("—" if sh.get(k) is None else f"{sh[k]:.1%}" for k in ("volume", "snap", "usage", "efficiency")) + " |")
    L += ["", "## Availability strata (realised, hindsight labels; diagnostic only)", "",
          "Contribution = mean over ALL rows of the paired difference inside the stratum (flagged + unflagged = pooled gap). Strata overlap except any / none.", ""]
    for p in ("PURE_minus_V4_MEF_AS_IS", "availability_features__V4_NO_AVAIL_minus_V4_MEF", "PURE_minus_V4_MEF_NO_AVAIL"):
        L += [f"### {p}", "", "| statistic | stratum | n rows | within-stratum gap | contribution to pooled gap |", "|---|---|---|---|---|"]
        for st in STATS:
            av = r["player"][st]["availability"][p]; d = dp(st)
            L.append(f"| {st} | (pooled) | {av['pooled_gap']['n']:,} | {f(av['pooled_gap'], d)} | — |")
            for k, v in av.items():
                if k == "pooled_gap":
                    continue
                L.append(f"| {st} | {k} | {v['n_rows']:,} | {f(v['within_stratum_gap'], d)} | {f(v['contribution_to_pooled_gap'], d)} |")
        L.append("")
    L += ["## Opponent", "", "### Gap by opponent tercile of PURE's prior-only allowed rate", "",
          "| statistic | feature | tercile | n | PURE − V4_MKT | PURE − V4_MEF |", "|---|---|---|---|---|---|"]
    for st in STATS:
        ot = r["player"][st]["opponent_terciles"]
        if not ot:
            continue
        for t in ("allows_least", "middle", "allows_most"):
            a = ot["PURE_minus_V4_MARKET_CLOSE"][t]; b = ot["PURE_minus_V4_MEF_AS_IS"][t]
            L.append(f"| {st} | {ot['feature']} | {t} | {a['n_rows']:,} | {f(a['within_stratum_gap'], dp(st))} | {f(b['within_stratum_gap'], dp(st))} |")
    L += ["", "### Residual opponent signal (cross-season LAD correction; MAE with the feature set − MAE with the scale term alone; < 0 = signal left)", "",
          "| statistic | arm | PURE V1 opponent features | positional prior-only | positional over-expected | ORACLE full-season positional |", "|---|---|---|---|---|---|"]
    for st in STATS:
        rs = r["player"][st].get("opponent_residual_signal")
        if not rs:
            continue
        for a, v in rs.items():
            L.append(f"| {st} | {a} | " + " | ".join(f(v.get(k), dp(st)) for k in ("pure_v1_opponent_features", "positional_prior_only",
                                                                                       "positional_over_expected_prior_only", "ORACLE_positional_full_season_loo")) + " |")
    L += ["", "## Team layer (team pass / rush attempts)", "", "| layer | n team-games | MAE PURE | MAE V4_MEF | MAE V4_MKT | PURE − V4_MKT | PURE − V4_MEF |", "|---|---|---|---|---|---|---|"]
    for layer, v in r["team_layer"].items():
        L.append(f"| {layer} | {v['n_team_games']:,} | {v['mae']['PURE_PLAYER_V1']:.3f} | {v['mae']['V4_MEF_AS_IS']:.3f} | {v['mae']['V4_MARKET_CLOSE']:.3f} | "
                 f"{f(v['PURE_minus_V4_MARKET_CLOSE'], 3)} | {f(v['PURE_minus_V4_MEF_AS_IS'], 3)} |")
    open(out, "w").write("\n".join(L) + "\n")


if __name__ == "__main__":
    base = os.path.join(ROOT, "research", "pure_gap")
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(base, "decomposition.json"),
         sys.argv[2] if len(sys.argv) > 2 else os.path.join(base, "DECOMPOSITION_TABLES.md"))
