#!/usr/bin/env python3
"""Render research/pure_player_v1/results.json (+ mutation.json) as RESULTS_TABLES.md and apply the
preregistered decision rule (docs/research/PURE_PLAYER_V1_PREREGISTRATION.md)."""
from __future__ import annotations

import argparse
import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
STATS = ["snap_share", "targets", "receptions", "receiving_yards", "carries", "rushing_yards", "passing_attempts", "completions", "passing_yards"]


def ci(c):
    return "—" if not c else f"[{c[0]:+.3f}, {c[1]:+.3f}]"


def player_table(block: dict, title: str) -> list[str]:
    out = [f"#### {title}", "", "| statistic | n player-games | n games | MAE ch | MAE ref | ΔMAE [95% CI] | RMSE ch | RMSE ref | ΔMSE [95% CI] | bias ch | bias ref | cov80 ch | cov80 ref | Brier ch | Brier ref | ΔBrier [95% CI] |",
           "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for st in STATS:
        v = block.get(st)
        if not v:
            continue
        out.append(f"| {st} | {v['n_player_games']} | {v['n_games']} | {v['mae_a']:.3f} | {v['mae_b']:.3f} | {v['delta_mae']:+.3f} {ci(v['delta_mae_ci95'])} | "
                   f"{v['rmse_a']:.3f} | {v['rmse_b']:.3f} | {v['delta_mse']:+.3f} {ci(v['delta_mse_ci95'])} | {v['bias_a']:+.3f} | {v['bias_b']:+.3f} | "
                   f"{v['cov80_a']:.3f} | {v['cov80_b']:.3f} | {v['brier_a']:.4f} | {v['brier_b']:.4f} | {v['delta_brier']:+.4f} {ci(v['delta_brier_ci95'])} |")
    return out + [""]


def team_table(block: dict, title: str) -> list[str]:
    out = [f"#### {title}", "", "| layer | n team-games | n games | MAE ch | MAE ref | ΔMAE [95% CI] | RMSE ch | RMSE ref | ΔMSE [95% CI] | bias ch | bias ref |",
           "|---|---|---|---|---|---|---|---|---|---|---|"]
    for x in ("pa", "ra", "plays", "pts"):
        v = block.get(x)
        if not v:
            continue
        out.append(f"| {x} | {v['n_team_games']} | {v['n_games']} | {v['mae_a']:.3f} | {v['mae_b']:.3f} | {v['delta_mae']:+.3f} {ci(v['delta_mae_ci95'])} | "
                   f"{v['rmse_a']:.3f} | {v['rmse_b']:.3f} | {v['delta_mse']:+.3f} {ci(v['delta_mse_ci95'])} | {v['bias_a']:+.3f} | {v['bias_b']:+.3f} |")
    return out + [""]


def verdict(r: dict) -> dict:
    blk = r["player"]["primary_2024_2025"]["PURE_PLAYER_V1__vs__PURE_EWM_BASELINE"]
    better = [s for s in STATS if s in blk and blk[s]["delta_mae"] < 0]
    sig_better = [s for s in STATS if s in blk and blk[s]["delta_mae_ci95"] and blk[s]["delta_mae_ci95"][1] < 0]
    worse = [s for s in STATS if s in blk and ((blk[s]["delta_mae_ci95"] and blk[s]["delta_mae_ci95"][0] > 0)
                                               or (blk[s]["delta_brier_ci95"] and blk[s]["delta_brier_ci95"][0] > 0))]
    scorable = [s for s in STATS if all((r["player"][f"season_{S}"]["PURE_PLAYER_V1__vs__PURE_EWM_BASELINE"].get(s) or {}).get("n_player_games", 0) >= 200
                                        for S in (2024, 2025))]
    if len(scorable) < 7:
        v = "BLOCKED_DATA"
    elif len(better) >= 6 and len(sig_better) >= 4 and not worse:
        v = "ACCEPTED_CHALLENGER"
    else:
        v = "REJECTED"
    return {"verdict": v, "mae_better": better, "mae_better_ci_excludes_0": sig_better, "significantly_worse": worse, "scorable": scorable}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=os.path.join(ROOT, "research", "pure_player_v1"))
    a = ap.parse_args()
    r = json.load(open(os.path.join(a.dir, "results.json")))
    v = verdict(r)
    L = ["# PURE_PLAYER_V1 — held-out tables (generated by scripts/research/pure_player_v1_render.py)", "",
         f"Preregistered rule verdict: **{v['verdict']}** — ΔMAE<0 on {len(v['mae_better'])}/9, CI<0 on {len(v['mae_better_ci_excludes_0'])}/9, "
         f"significantly worse (MAE or Brier): {v['significantly_worse'] or 'none'}; scorable: {len(v['scorable'])}/9.", "",
         "ch = first-named arm (challenger), ref = second; Δ = ch − ref (negative = challenger better). CIs: paired game-clustered bootstrap, B=1000.", ""]
    for sc, pairs in r["player"].items():
        L.append(f"## Player layers — {sc}"); L.append("")
        for pair, blk in pairs.items():
            L += player_table(blk, pair.replace("__vs__", " vs "))
    L.append("## Player layers by position group — primary 2024+2025, PURE_PLAYER_V1 vs PURE_EWM_BASELINE"); L.append("")
    for g, blk in r["player_by_group"].items():
        L += player_table(blk, g)
    for sc, pairs in r["team"].items():
        L.append(f"## Team layers — {sc}"); L.append("")
        for pair, blk in pairs.items():
            if blk:
                L += team_table(blk, pair.replace("__vs__", " vs "))
    L.append("## Market ticker inventory vs full sports population (2025, diagnostic)"); L.append("")
    sel = r["market_inventory_selection_2025"]
    L.append(f"Kalshi-listed (player, game) pairs in the 2025 archive: {sel['listed_player_games_any_stat']}"); L.append("")
    L.append("| arm | statistic | n all | n listed | MAE all | MAE listed | MAE not listed | bias listed | bias not listed |"); L.append("|---|---|---|---|---|---|---|---|---|")
    for arm, d in sel["by_arm"].items():
        for st in STATS:
            x = d.get(st)
            if x:
                L.append(f"| {arm} | {st} | {x['n_all']} | {x['n_market_listed']} | {x['mae_all']} | {x['mae_market_listed']} | {x['mae_not_listed']} | {x['bias_market_listed']} | {x['bias_not_listed']} |")
    L.append("")
    with open(os.path.join(a.dir, "RESULTS_TABLES.md"), "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(json.dumps(v))


if __name__ == "__main__":
    main()
