#!/usr/bin/env python3
"""Regenerate research/hypothesis_registry/registry.md from the canonical per-hypothesis JSON files.

The JSON files are the source of truth. The table was previously maintained by hand, which is how a
hypothesis can end up with one status in its own file and a different impression in the summary. This makes
the table a projection of the files, so the two cannot drift.

The table surfaces `decision_executed` where present, because a standing rule whose decision has already been
acted on reads as untouched when only `status` is shown -- which is exactly the confusion that prompted this
script.
"""
from __future__ import annotations

import glob
import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
REG = os.path.join(ROOT, "research", "hypothesis_registry")

HEADER = """# Hypothesis registry

Generated by `python3 scripts/research/rebuild_registry.py` from the per-hypothesis JSON files, which are the
source of truth. Do not edit this table by hand.

`status` is the hypothesis's own lifecycle. `decision executed` records an action already taken as a
consequence of it -- a standing rule can be live *and* have already forced a change.

| id | status | decision executed | target | expected direction |
|---|---|---|---|---|
"""


def main():
    files = sorted(glob.glob(os.path.join(REG, "H-*.json")))
    if not files:
        print("no hypothesis files found", file=sys.stderr)
        return 1
    rows = []
    for f in files:
        h = json.load(open(f))
        rows.append("| `{id}` | {status} | {dec} | {target} | {exp} |".format(
            id=h["id"], status=h.get("status", "?"),
            dec=(h.get("decision_executed", "") or "—")[:70].replace("\n", " "),
            target=(h.get("target", "") or "")[:70].replace("\n", " "),
            exp=(h.get("expected_direction", "") or "")[:80].replace("\n", " ")))
    out = os.path.join(REG, "registry.md")
    with open(out, "w") as fh:
        fh.write(HEADER + "\n".join(rows) + "\n")
    print(f"wrote {out} with {len(rows)} hypotheses")
    counts = {}
    for f in files:
        s = json.load(open(f)).get("status", "?")
        counts[s] = counts.get(s, 0) + 1
    for k, v in sorted(counts.items()):
        print(f"  {k}: {v}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
